export const ROLES = {
  ADMIN: 'admin',
  GROUPS: 'groups',
  CLIENT: 'client',
  CLIENT_GOD: 'client_god',
  CORPORATE: 'corporate',
  HEAD_OFFICE: 'head_office',
  REGIONAL: 'regional',
  BRANCH: 'branch',
  LABOR: 'labor',
  PARTNER: 'partner',
  REPORTER: 'reporter',
  MEDIA: 'media',
};

export const ROLE_SETS = {
  ADMIN: [ROLES.ADMIN, ROLES.GROUPS],
  ADMIN_EXTENDED: [ROLES.ADMIN, ROLES.GROUPS, ROLES.CORPORATE, ROLES.HEAD_OFFICE, ROLES.REGIONAL, ROLES.BRANCH],
  CORPORATE: [ROLES.CORPORATE],
  FRANCHISE: [ROLES.CORPORATE, ROLES.HEAD_OFFICE, ROLES.REGIONAL, ROLES.BRANCH],
  FRANCHISE_OFFICE: [ROLES.HEAD_OFFICE, ROLES.REGIONAL, ROLES.BRANCH],
  CLIENT: [ROLES.CLIENT, ROLES.CLIENT_GOD],
  PARTNER: [ROLES.PARTNER],
  LABOR: [ROLES.LABOR],
  MEDIA: [ROLES.CLIENT, ROLES.CLIENT_GOD, ROLES.MEDIA],
  MEDIA_DASHBOARD: [ROLES.PARTNER, ROLES.CLIENT, ROLES.CLIENT_GOD, ROLES.MEDIA],
};
