-- ============================================
-- 4. MYNEEDY - SERVICE MANAGEMENT MODULE
-- ============================================

-- Service Categories
CREATE TABLE needy_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE,
  parent_id INT NULL,
  icon VARCHAR(255),
  description TEXT,
  is_active TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES needy_categories(id) ON DELETE SET NULL,
  INDEX idx_slug (slug),
  INDEX idx_parent_id (parent_id),
  INDEX idx_is_active (is_active),
  INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Default Categories
INSERT INTO needy_categories (name, slug, description) VALUES
('Home Services', 'home-services', 'Plumbing, Electrical, Cleaning, etc.'),
('Healthcare', 'healthcare', 'Doctors, Nurses, Medical Services'),
('Education', 'education', 'Tutors, Training, Coaching'),
('Beauty & Wellness', 'beauty-wellness', 'Salon, Spa, Fitness'),
('Repair & Maintenance', 'repair-maintenance', 'AC, Appliance, Vehicle Repair'),
('Event Services', 'event-services', 'Catering, Photography, Decoration'),
('Professional Services', 'professional-services', 'Legal, Accounting, Consulting'),
('Transportation', 'transportation', 'Taxi, Delivery, Moving'),
('Pet Services', 'pet-services', 'Grooming, Training, Veterinary'),
('Other Services', 'other-services', 'Miscellaneous Services');

-- Service Providers
CREATE TABLE needy_service_providers (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  business_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT,
  category_id INT,
  service_type ENUM('doorstep', 'center', 'online', 'manpower') DEFAULT 'doorstep',
  contact_person VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(254),
  address TEXT,
  country INT,
  state INT,
  district INT,
  pincode VARCHAR(10),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  logo VARCHAR(255),
  banner_image VARCHAR(255),
  gallery JSON,
  working_hours JSON,
  service_areas JSON,
  pricing_type ENUM('fixed', 'hourly', 'negotiable') DEFAULT 'fixed',
  min_price DECIMAL(10, 2),
  max_price DECIMAL(10, 2),
  rating DECIMAL(3, 2) DEFAULT 0.00,
  total_reviews INT DEFAULT 0,
  total_bookings INT DEFAULT 0,
  is_verified TINYINT DEFAULT 0,
  is_featured TINYINT DEFAULT 0,
  is_active TINYINT DEFAULT 1,
  status ENUM('pending', 'approved', 'rejected', 'suspended') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES needy_categories(id) ON DELETE SET NULL,
  INDEX idx_user_id (user_id),
  INDEX idx_slug (slug),
  INDEX idx_category_id (category_id),
  INDEX idx_service_type (service_type),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  INDEX idx_is_featured (is_featured),
  INDEX idx_rating (rating),
  FULLTEXT idx_search (business_name, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Service Listings
CREATE TABLE needy_services (
  id INT PRIMARY KEY AUTO_INCREMENT,
  provider_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  description TEXT,
  category_id INT,
  service_type ENUM('doorstep', 'center', 'online', 'manpower') DEFAULT 'doorstep',
  price DECIMAL(10, 2),
  pricing_unit VARCHAR(50),
  duration INT,
  duration_unit ENUM('minutes', 'hours', 'days') DEFAULT 'hours',
  images JSON,
  features JSON,
  requirements TEXT,
  terms_conditions TEXT,
  is_active TINYINT DEFAULT 1,
  views_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (provider_id) REFERENCES needy_service_providers(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES needy_categories(id) ON DELETE SET NULL,
  INDEX idx_provider_id (provider_id),
  INDEX idx_slug (slug),
  INDEX idx_category_id (category_id),
  INDEX idx_service_type (service_type),
  INDEX idx_is_active (is_active),
  FULLTEXT idx_search (title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Service Bookings
CREATE TABLE needy_bookings (
  id INT PRIMARY KEY AUTO_INCREMENT,
  booking_number VARCHAR(50) UNIQUE NOT NULL,
  service_id INT NOT NULL,
  provider_id INT NOT NULL,
  customer_id INT NOT NULL,
  booking_date DATE NOT NULL,
  booking_time TIME,
  service_address TEXT,
  customer_name VARCHAR(100),
  customer_phone VARCHAR(20),
  customer_email VARCHAR(254),
  special_instructions TEXT,
  status ENUM('pending', 'confirmed', 'in_progress', 'completed', 'cancelled', 'refunded') DEFAULT 'pending',
  payment_status ENUM('pending', 'paid', 'refunded') DEFAULT 'pending',
  payment_method VARCHAR(50),
  amount DECIMAL(10, 2),
  discount DECIMAL(10, 2) DEFAULT 0.00,
  tax DECIMAL(10, 2) DEFAULT 0.00,
  total_amount DECIMAL(10, 2),
  cancellation_reason TEXT,
  cancelled_by INT,
  cancelled_at TIMESTAMP NULL,
  completed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (service_id) REFERENCES needy_services(id) ON DELETE CASCADE,
  FOREIGN KEY (provider_id) REFERENCES needy_service_providers(id) ON DELETE CASCADE,
  FOREIGN KEY (customer_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_booking_number (booking_number),
  INDEX idx_service_id (service_id),
  INDEX idx_provider_id (provider_id),
  INDEX idx_customer_id (customer_id),
  INDEX idx_status (status),
  INDEX idx_booking_date (booking_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Service Reviews & Ratings
CREATE TABLE needy_reviews (
  id INT PRIMARY KEY AUTO_INCREMENT,
  service_id INT NOT NULL,
  provider_id INT NOT NULL,
  booking_id INT,
  user_id INT NOT NULL,
  rating DECIMAL(2, 1) NOT NULL,
  review_title VARCHAR(255),
  review_text TEXT,
  images JSON,
  is_verified_purchase TINYINT DEFAULT 0,
  helpful_count INT DEFAULT 0,
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (service_id) REFERENCES needy_services(id) ON DELETE CASCADE,
  FOREIGN KEY (provider_id) REFERENCES needy_service_providers(id) ON DELETE CASCADE,
  FOREIGN KEY (booking_id) REFERENCES needy_bookings(id) ON DELETE SET NULL,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_service_id (service_id),
  INDEX idx_provider_id (provider_id),
  INDEX idx_user_id (user_id),
  INDEX idx_rating (rating),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

