-- ============================================
-- 5. LABOR MANAGEMENT MODULE
-- ============================================

-- Labor Categories/Skills
CREATE TABLE labor_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE,
  icon VARCHAR(255),
  description TEXT,
  is_active TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_slug (slug),
  INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert Default Labor Categories
INSERT INTO labor_categories (name, slug) VALUES
('Construction Worker', 'construction-worker'),
('Electrician', 'electrician'),
('Plumber', 'plumber'),
('Carpenter', 'carpenter'),
('Painter', 'painter'),
('Welder', 'welder'),
('Mason', 'mason'),
('Driver', 'driver'),
('Security Guard', 'security-guard'),
('Housekeeping', 'housekeeping'),
('Cook/Chef', 'cook-chef'),
('Gardener', 'gardener'),
('Mechanic', 'mechanic'),
('Tailor', 'tailor'),
('Factory Worker', 'factory-worker'),
('Delivery Person', 'delivery-person'),
('Helper/Assistant', 'helper-assistant'),
('Other', 'other');

-- Labor Profiles
CREATE TABLE labor_profiles (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL UNIQUE,
  category_id INT,
  full_name VARCHAR(100) NOT NULL,
  photo VARCHAR(255),
  date_of_birth DATE,
  age INT,
  gender ENUM('Male', 'Female', 'Other'),
  phone VARCHAR(20),
  alternate_phone VARCHAR(20),
  email VARCHAR(254),
  address TEXT,
  country INT,
  state INT,
  district INT,
  pincode VARCHAR(10),
  current_location VARCHAR(255),
  aadhar_number VARCHAR(20),
  pan_number VARCHAR(20),
  driving_license VARCHAR(50),
  other_id_proof VARCHAR(255),
  skills JSON,
  experience_years INT DEFAULT 0,
  education_level VARCHAR(100),
  languages_known JSON,
  preferred_work_type ENUM('full_time', 'part_time', 'contract', 'daily_wage') DEFAULT 'full_time',
  expected_salary DECIMAL(10, 2),
  salary_type ENUM('monthly', 'daily', 'hourly', 'project') DEFAULT 'monthly',
  availability ENUM('immediate', 'within_week', 'within_month', 'not_available') DEFAULT 'immediate',
  willing_to_relocate TINYINT DEFAULT 0,
  emergency_contact_name VARCHAR(100),
  emergency_contact_phone VARCHAR(20),
  emergency_contact_relation VARCHAR(50),
  bio TEXT,
  resume_file VARCHAR(255),
  certificates JSON,
  references JSON,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  total_reviews INT DEFAULT 0,
  total_jobs_completed INT DEFAULT 0,
  is_verified TINYINT DEFAULT 0,
  is_active TINYINT DEFAULT 1,
  status ENUM('available', 'employed', 'not_available') DEFAULT 'available',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES labor_categories(id) ON DELETE SET NULL,
  INDEX idx_user_id (user_id),
  INDEX idx_category_id (category_id),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  INDEX idx_availability (availability),
  FULLTEXT idx_search (full_name, skills, bio)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Labor Job Postings
CREATE TABLE labor_jobs (
  id INT PRIMARY KEY AUTO_INCREMENT,
  posted_by INT NOT NULL,
  job_title VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  category_id INT,
  description TEXT,
  requirements TEXT,
  job_type ENUM('full_time', 'part_time', 'contract', 'daily_wage', 'temporary') DEFAULT 'full_time',
  experience_required INT DEFAULT 0,
  number_of_positions INT DEFAULT 1,
  salary_min DECIMAL(10, 2),
  salary_max DECIMAL(10, 2),
  salary_type ENUM('monthly', 'daily', 'hourly', 'project') DEFAULT 'monthly',
  location VARCHAR(255),
  country INT,
  state INT,
  district INT,
  work_hours VARCHAR(100),
  benefits TEXT,
  contact_person VARCHAR(100),
  contact_phone VARCHAR(20),
  contact_email VARCHAR(254),
  application_deadline DATE,
  start_date DATE,
  is_active TINYINT DEFAULT 1,
  status ENUM('open', 'closed', 'filled') DEFAULT 'open',
  views_count INT DEFAULT 0,
  applications_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (posted_by) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES labor_categories(id) ON DELETE SET NULL,
  INDEX idx_posted_by (posted_by),
  INDEX idx_slug (slug),
  INDEX idx_category_id (category_id),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  FULLTEXT idx_search (job_title, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Labor Job Applications
CREATE TABLE labor_job_applications (
  id INT PRIMARY KEY AUTO_INCREMENT,
  job_id INT NOT NULL,
  labor_id INT NOT NULL,
  user_id INT NOT NULL,
  application_status ENUM('applied', 'shortlisted', 'interviewed', 'selected', 'rejected', 'withdrawn') DEFAULT 'applied',
  cover_letter TEXT,
  expected_salary DECIMAL(10, 2),
  available_from DATE,
  resume_file VARCHAR(255),
  additional_documents JSON,
  notes TEXT,
  applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (job_id) REFERENCES labor_jobs(id) ON DELETE CASCADE,
  FOREIGN KEY (labor_id) REFERENCES labor_profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  UNIQUE KEY unique_job_application (job_id, labor_id),
  INDEX idx_job_id (job_id),
  INDEX idx_labor_id (labor_id),
  INDEX idx_application_status (application_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Labor Work History
CREATE TABLE labor_work_history (
  id INT PRIMARY KEY AUTO_INCREMENT,
  labor_id INT NOT NULL,
  employer_name VARCHAR(255),
  job_title VARCHAR(100),
  job_description TEXT,
  start_date DATE,
  end_date DATE,
  is_current TINYINT DEFAULT 0,
  location VARCHAR(255),
  salary DECIMAL(10, 2),
  leaving_reason TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (labor_id) REFERENCES labor_profiles(id) ON DELETE CASCADE,
  INDEX idx_labor_id (labor_id),
  INDEX idx_is_current (is_current)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Labor Reviews
CREATE TABLE labor_reviews (
  id INT PRIMARY KEY AUTO_INCREMENT,
  labor_id INT NOT NULL,
  reviewer_id INT NOT NULL,
  job_id INT,
  rating DECIMAL(2, 1) NOT NULL,
  review_title VARCHAR(255),
  review_text TEXT,
  work_quality_rating DECIMAL(2, 1),
  punctuality_rating DECIMAL(2, 1),
  behavior_rating DECIMAL(2, 1),
  status ENUM('pending', 'approved', 'rejected') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (labor_id) REFERENCES labor_profiles(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewer_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (job_id) REFERENCES labor_jobs(id) ON DELETE SET NULL,
  INDEX idx_labor_id (labor_id),
  INDEX idx_reviewer_id (reviewer_id),
  INDEX idx_rating (rating),
  INDEX idx_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

