-- ============================================
-- 6. MYSHOP - E-COMMERCE MODULE
-- ============================================

-- Product Categories
CREATE TABLE shop_categories (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) UNIQUE,
  parent_id INT NULL,
  icon VARCHAR(255),
  image VARCHAR(255),
  description TEXT,
  is_active TINYINT DEFAULT 1,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (parent_id) REFERENCES shop_categories(id) ON DELETE SET NULL,
  INDEX idx_slug (slug),
  INDEX idx_parent_id (parent_id),
  INDEX idx_is_active (is_active),
  INDEX idx_sort_order (sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shops/Stores
CREATE TABLE shops (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  shop_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  shop_type ENUM('shop', 'local', 'resale', 'brands', 'wholesale', 'ecoshop') DEFAULT 'shop',
  description TEXT,
  logo VARCHAR(255),
  banner_image VARCHAR(255),
  contact_person VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(254),
  address TEXT,
  country INT,
  state INT,
  district INT,
  pincode VARCHAR(10),
  latitude DECIMAL(10, 8),
  longitude DECIMAL(11, 8),
  business_license VARCHAR(255),
  gst_number VARCHAR(50),
  pan_number VARCHAR(50),
  bank_details JSON,
  working_hours JSON,
  delivery_options JSON,
  payment_methods JSON,
  return_policy TEXT,
  shipping_policy TEXT,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  total_reviews INT DEFAULT 0,
  total_products INT DEFAULT 0,
  total_orders INT DEFAULT 0,
  is_verified TINYINT DEFAULT 0,
  is_featured TINYINT DEFAULT 0,
  is_active TINYINT DEFAULT 1,
  status ENUM('pending', 'approved', 'rejected', 'suspended') DEFAULT 'pending',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_user_id (user_id),
  INDEX idx_slug (slug),
  INDEX idx_shop_type (shop_type),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  INDEX idx_is_featured (is_featured),
  FULLTEXT idx_search (shop_name, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products
CREATE TABLE shop_products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  shop_id INT NOT NULL,
  category_id INT,
  product_name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) UNIQUE,
  sku VARCHAR(100) UNIQUE,
  description TEXT,
  short_description VARCHAR(500),
  product_type ENUM('physical', 'digital', 'service') DEFAULT 'physical',
  condition ENUM('new', 'used', 'refurbished') DEFAULT 'new',
  brand VARCHAR(100),
  manufacturer VARCHAR(100),
  images JSON,
  thumbnail VARCHAR(255),
  price DECIMAL(10, 2) NOT NULL,
  compare_price DECIMAL(10, 2),
  cost_price DECIMAL(10, 2),
  tax_rate DECIMAL(5, 2) DEFAULT 0.00,
  stock_quantity INT DEFAULT 0,
  low_stock_threshold INT DEFAULT 5,
  weight DECIMAL(10, 2),
  weight_unit VARCHAR(10),
  dimensions JSON,
  variants JSON,
  specifications JSON,
  features JSON,
  tags JSON,
  meta_title VARCHAR(255),
  meta_description TEXT,
  meta_keywords VARCHAR(255),
  is_featured TINYINT DEFAULT 0,
  is_active TINYINT DEFAULT 1,
  status ENUM('draft', 'published', 'out_of_stock', 'discontinued') DEFAULT 'draft',
  views_count INT DEFAULT 0,
  sales_count INT DEFAULT 0,
  rating DECIMAL(3, 2) DEFAULT 0.00,
  total_reviews INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE,
  FOREIGN KEY (category_id) REFERENCES shop_categories(id) ON DELETE SET NULL,
  INDEX idx_shop_id (shop_id),
  INDEX idx_category_id (category_id),
  INDEX idx_slug (slug),
  INDEX idx_sku (sku),
  INDEX idx_status (status),
  INDEX idx_is_active (is_active),
  INDEX idx_is_featured (is_featured),
  INDEX idx_price (price),
  FULLTEXT idx_search (product_name, description, brand)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shopping Cart
CREATE TABLE shop_cart (
  id INT PRIMARY KEY AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT NOT NULL,
  shop_id INT NOT NULL,
  quantity INT DEFAULT 1,
  variant_options JSON,
  price DECIMAL(10, 2),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES shop_products(id) ON DELETE CASCADE,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE,
  UNIQUE KEY unique_cart_item (user_id, product_id, variant_options(100)),
  INDEX idx_user_id (user_id),
  INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Orders
CREATE TABLE shop_orders (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_number VARCHAR(50) UNIQUE NOT NULL,
  user_id INT NOT NULL,
  shop_id INT NOT NULL,
  customer_name VARCHAR(100),
  customer_email VARCHAR(254),
  customer_phone VARCHAR(20),
  shipping_address JSON,
  billing_address JSON,
  subtotal DECIMAL(10, 2) NOT NULL,
  tax DECIMAL(10, 2) DEFAULT 0.00,
  shipping_cost DECIMAL(10, 2) DEFAULT 0.00,
  discount DECIMAL(10, 2) DEFAULT 0.00,
  total_amount DECIMAL(10, 2) NOT NULL,
  payment_method VARCHAR(50),
  payment_status ENUM('pending', 'paid', 'failed', 'refunded') DEFAULT 'pending',
  payment_transaction_id VARCHAR(255),
  order_status ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled', 'returned') DEFAULT 'pending',
  shipping_method VARCHAR(100),
  tracking_number VARCHAR(100),
  notes TEXT,
  cancellation_reason TEXT,
  cancelled_by INT,
  cancelled_at TIMESTAMP NULL,
  shipped_at TIMESTAMP NULL,
  delivered_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (shop_id) REFERENCES shops(id) ON DELETE CASCADE,
  FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_order_number (order_number),
  INDEX idx_user_id (user_id),
  INDEX idx_shop_id (shop_id),
  INDEX idx_order_status (order_status),
  INDEX idx_payment_status (payment_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Order Items
CREATE TABLE shop_order_items (
  id INT PRIMARY KEY AUTO_INCREMENT,
  order_id INT NOT NULL,
  product_id INT NOT NULL,
  product_name VARCHAR(255),
  product_sku VARCHAR(100),
  variant_options JSON,
  quantity INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  tax DECIMAL(10, 2) DEFAULT 0.00,
  total DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (order_id) REFERENCES shop_orders(id) ON DELETE CASCADE,
  FOREIGN KEY (product_id) REFERENCES shop_products(id) ON DELETE CASCADE,
  INDEX idx_order_id (order_id),
  INDEX idx_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

